name: changelog
description: A changelog generation tool using git data and Angular conventions
version: 0.0.1
author: Andres Araujo <a.araujo.azua.com>
#homepage: https://www.example.com
dependencies:
  unscripted: ">=0.6.1+1 <0.7.0"
  git: ">=0.4.4+1 <0.5.0"
dev_dependencies:
  test: any
