name: changelog
description: A changelog generation tool using git data and Angular conventions
version: 0.1.0
author: Andres Araujo <a.araujo.azua.com>
#homepage: https://www.example.com
dependencies:
  unscripted: ">=0.6.1+1 <0.7.0"
  git: ">=0.4.4+1 <0.5.0"
  intl: ">=0.12.3 <0.13.0"

  mustache: "^0.2.3"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  grinder: ">=0.7.0 <0.8.0"
  tuneup: ">=0.0.5+6 <0.1.0"
